dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
  - /^hotfix-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm install
before_script:
  - ./tools/runGanacheCli.sh </dev/null 1>/dev/null 2>&1 &
  - npm run compile
script:
  - npm run test
  - npm run build-package
after_script:
  - kill $(ps aux | grep 'ganache-cli' | awk '{print $2}')
