dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
  - /^hotfix-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm ci
before_script:
  - npm run ganache
  - npm run compile-all
script:
  - npm run lint
  - npm run test
  - npm run build-package
after_script:
  - kill $(ps aux | grep 'ganache-cli' | awk '{print $2}')
